command /clear-chat:
	aliases: /cc, /clearchat, /chatclear, /chat-clear
	permission: msd.cc
	permission message: "&r&fYou do not have permission to run this command."
	trigger:
		set {_p} to player
		loop all players:
			loop 1000 times:
				send " " to loop-player
			send "&3---------------- &b| &cM&6S&cD&b |&3 ----------------"
			send " "
		broadcast "  &3%{_p}% &ehas cleared the chat"
		loop all players:
			send " "
			send "&3---------------- &b| &cM&6S&cD&b |&3 ----------------"